language: r

repos:
  CRAN: https://cloud.r-project.org
  folkehelseinstituttet: https://folkehelseinstituttet.github.io/drat/
  euromomo: https://euromomonetwork.github.io/drat/
  raubreywhite: https://raubreywhite.github.io/drat/

r_packages:
- covr
- drat
- pkgdown
- lintr
- styler
- devtools
- data.table
- stringr
- glue
- lubridate
- readxl
- zoo
- crayon
- fs
- utils

before_install:
- bash travis/make.sh
before_script:
- bash travis/data.sh
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  travis/drat.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  travis/styler.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && Rscript
  -e 'Sys.sleep(30);install.packages("fhidata",repos="https://folkehelseinstituttet.github.io/drat/");pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
